nhsuk/betahealth

- .gitignore
- app/controllers/index.js
- config/express.js
- config/routes.js
- gulp/tasks/lint.js
- package.json
- test/unit/.eslintrc
- test/unit/common.js
- test/unit/controllers/index.test.js
- test/unit/mocha.opts
Create basic unit test setup.
- Refactor controllers to be more testable
- Add [mocha framework](https://mochajs.org/) for unit testing
> Unit tests

- app/controllers/elements.js
- app/views/elements.nunjucks
- config/routes.js
- test/unit/controllers/elements.test.js
This allows us to see how elements line up on a page and their default style
> Add a basic elements page

- assets/stylesheets/style.scss
- assets/stylesheets/trumps/_beta-placeholder.scss
The structure is a combination of ITCSS by Harry Roberts
and how NHSUK currently structures components and elements
> Create initial sass folder structure

- assets/stylesheets/environment/settings/_colours.scss
- assets/stylesheets/environment/tools/_mixins.scss
- assets/stylesheets/style.scss
> Add colour vars, tint and shade mixins

- assets/stylesheets/environment/tools/_placeholders.scss
We're making a conscious decision to incorporate our own placeholders etc as opposed to using a library.
> Add clearfix placeholder

- app/views/_includes/global/analytics.nunjucks
- app/views/_includes/global/head.nunjucks
- app/views/layout.nunjucks
Break out `<head>` and analytics blocks into global includes.
> Global includes

- .travis.yml
- config/express.js
- gulp/tasks/lint.js
- gulp/tasks/serve.js
Run unit tests and linting on Travis
> Add Travis CI configuration

- app/views/elements.nunjucks
- assets/stylesheets/environment/settings/_colours.scss
- assets/stylesheets/style.scss
- assets/stylesheets/units/_images.scss
- assets/stylesheets/units/_links.scss
- assets/stylesheets/units/_lists.scss
- assets/stylesheets/units/_quotes.scss
Add basic styles for:
- Lists
- Links
- Images
- Quotes
> Add some initial base unit styles

- app/views/stomach-ache.nunjucks
- assets/stylesheets/components/_callout.scss
- assets/stylesheets/style.scss
Create basic callouts "See your GP", "Call 111", "Go to A+E"
> Component callouts

- app/views/layouts/layout.nunjucks
- app/views/stomach-ache.nunjucks
- assets/stylesheets/components/_skiplinks.scss
- assets/stylesheets/style.scss
> Add #content skiplink

- .gitignore
- README.md
- app.json
- app/views/_includes/global/head.nunjucks
- app/views/_includes/global/header.nunjucks
- app/views/index.nunjucks
- assets/stylesheets/components/_global-header.scss
- assets/stylesheets/environment/generic/_shared.scss
- assets/stylesheets/environment/settings/_fonts.scss
- assets/stylesheets/environment/settings/_globals.scss
- assets/stylesheets/environment/settings/_typography.scss
- assets/stylesheets/environment/tools/mixins/_typography.scss
- assets/stylesheets/nhsuk.scss
- config/config.js
- config/express.js
- gulp/paths.js
- gulp/tasks/build.js
- gulp/tasks/css.js
- gulp/tasks/fonts.js
- package.json
The font is hosted on a separate server and a gulp task handles
the source during the build step.
> Add support for FS Me font

- app/views/_includes/cookie-message.nunjucks
- app/views/_includes/global/foot.nunjucks
- app/views/cookies.nunjucks
- app/views/layouts/layout.nunjucks
- assets/javascripts/modules/cookie-message.js
- assets/javascripts/nhsuk.js
- assets/stylesheets/components/_notification-banner.scss
- assets/stylesheets/nhsuk.scss
- gulp/tasks/build.js
- gulp/tasks/watch.js
- gulp/tasks/webpack.js
- package.json
- webpack.config.js
Add dynamic cookie message banner. 
The banner is displayed by default if no javascript has loaded. After that it will disappear after the first page view by setting and reading a cookie.
> Cookie message

- app/controllers/clinical-assurance.js
- app/views/_includes/global/footer.nunjucks
- app/views/clinical-assurance.nunjucks
- config/routes.js
- test/unit/controllers/clinical-assurance.test.js
Add basic clinical assurance page
> Clinical assurance

- app/views/_layouts/content-page.nunjucks
- assets/stylesheets/components/_callout.scss
- assets/stylesheets/environment/tools/mixins/_css3.scss
- assets/stylesheets/environment/tools/placeholders/_grid-layout.scss
- assets/stylesheets/nhsuk.scss
- assets/stylesheets/objects/_grid.scss
Visually change component layout but keep the ordering of them sensible for mobile, when stacked on top of each other, and assistive tech.
> Element stack

- app/views/_layouts/content-page.nunjucks
- assets/javascripts/modules/cookie-message.js
- assets/stylesheets/components/_callout.scss
- assets/stylesheets/components/_global-footer.scss
- assets/stylesheets/components/_inline-list.scss
- assets/stylesheets/components/_notification-banner.scss
- assets/stylesheets/environment/generic/_shared.scss
- assets/stylesheets/environment/settings/_colours.scss
- assets/stylesheets/units/_tables.scss
Add some basic accessibility improvements including:
- Improve contrast on cookie banner
- Wrap content page in article element
Also includes:
- colour palette rework to add new grey
- tighten spacing around banners and footer
> Basic a11y improvements

- app/middleware/locals.js
- app/views/_includes/global/head.nunjucks
- assets/javascripts/modules/cookie-message.js
- config/config.js
- config/express.js
- package.json
This separates the global template locals into their own middleware
and adds the absolute url to the assets path.
> Move template locals into separate middleware

- app/middleware/check-secure.js
- app/middleware/locals.js
- config/config.js
- config/express.js
This separates checking of https status in middleware which sets it on the
request for use in subsequent middlewares
> Handle https check in separate middleware

- app.js
- app/views/_includes/global/footer.nunjucks
- app/views/_layouts/content-page.nunjucks
- app/views/stomach-ache.nunjucks
- config/config.js
- config/express.js
- config/routes.js
- lib/logger.js
- package.json
Some tweaks to stomach ache page:
• source order
• copy
• /symptoms/ spelling correction
• remove all licence references
> Release - stomach ache tweaks

- app/views/_includes/feedback-form.nunjucks
- app/views/_includes/feedback-message.nunjucks
- app/views/_layouts/content-page.nunjucks
- app/views/_layouts/nhsuk.nunjucks
- assets/stylesheets/components/_callout.scss
- assets/stylesheets/components/_error.scss
- assets/stylesheets/components/_label.scss
- assets/stylesheets/components/_notification-banner.scss
- assets/stylesheets/environment/settings/_colours.scss
- assets/stylesheets/environment/tools/_utilities.scss
- assets/stylesheets/environment/tools/mixins/_typography.scss
- assets/stylesheets/environment/tools/placeholders/_grid-layout.scss
- assets/stylesheets/nhsuk.scss
- assets/stylesheets/objects/_page-section.scss
- assets/stylesheets/units/_buttons.scss
- assets/stylesheets/units/_forms.scss
- assets/stylesheets/units/_lists.scss
Add basic html and css for the feedback banner. Non functional.
> Add feedback banner (non-functional html and css)

- app/controllers/stomach-ache.js
- app/views/_includes/feedback-message.nunjucks
- app/views/_includes/new-site-message.nunjucks
- app/views/_layouts/nhsuk.nunjucks
> Only show feedback in pages that require it

- bin/run-acceptance-tests.sh
- test/unit/lib/feedback-api.js
Fake time was being called on current date which now fails tests
since the day it was written... :/
> Fix feedback api unit test

- app/middleware/feedback.js
- app/views/_includes/new-site-message.nunjucks
- app/views/_layouts/nhsuk.nunjucks
- config/config.js
This allows the form to be disabled on a particular environment if
necessary
> Wrap feedback form in a feature flag

- app/views/_includes/feedback-form.nunjucks
- app/views/_includes/new-site-message.nunjucks
- assets/javascripts/modules/feedback-form.js
- assets/javascripts/nhsuk.js
- package.json
Re-orders the position of the form in the DOM and shows and hides it based
on basic interaction
> Add initial JS enhancement to feedback form

- config/express.js
This adds the domain webtrends makes a call to for a gif it uses for tracking
> CSP update

- assets/stylesheets/components/_link-list.scss
- assets/stylesheets/components/_local-header.scss
- assets/stylesheets/components/_section-unit.scss
- assets/stylesheets/units/_lists.scss
Keep the spacing consistent around elements between different screen
widths
> Tweak spacing around section-unit and link-list

- app/views/headache.nunjucks
- app/views/index.nunjucks
- assets/stylesheets/nhsuk.scss
- assets/stylesheets/units/_hr.scss
- config/routes.js
This PR adds a basic page for headache's.
It also adds an initial style for `hr` units as they were originally part of the content but have decided to leave the new unit in as a separate commit for now as this element will be used again in the future.
> Add headache to symptoms

- app/middleware/feedback.js
- package.json
This reverts commit 9ddd3e71764d8884b098707de6951e00a3afcdc4.
> Revert "Store user IP address in feedback"

- app/controllers/content-page.js
- app/middleware/content-api.js
- app/middleware/guide-container.js
- app/middleware/guide.js
- app/middleware/set-feedback.js
- app/views/_layouts/content-simple.nunjucks
- app/views/_macros/components.nunjucks
- assets/stylesheets/components/_article-pagination.scss
- assets/stylesheets/components/_link-list.scss
- assets/stylesheets/environment/settings/_colours.scss
- assets/stylesheets/environment/tools/placeholders/_layout.scss
- assets/stylesheets/nhsuk.scss
- assets/stylesheets/units/_lists.scss
- config/content-router.js
- config/express.js
- config/routes.js
- lib/content-api.js
- package.json
- test/unit/controllers/content-page.test.js
This adds support for guide pages.
It involves some changes to the controllers serving the pages and the current content API library.
> Guide layouts

- app/middleware/guide-container.js
- app/views/_includes/global/head.nunjucks
- app/views/_macros/components.nunjucks
Adds the guide title to <title> and fixes bug in redirect where
the without the trailing slash the first guide page would go to the
wrong url
> Improve guide page support

- app/middleware/guide.js
- app/middleware/locals.js
- app/views/_includes/global/head.nunjucks
- app/views/_macros/components.nunjucks
- assets/javascripts/modules/analytics.js
- content/conditions/fungal-nail-infection/manifest.json
- content/conditions/hand-foot-and-mouth-disease/manifest.json
- content/conditions/head-lice/manifest.json
- content/conditions/shingles/manifest.json
- content/conditions/warts/manifest.json
- content/symptoms/rashes-in-babies-and-children/manifest.json
Tracking is currently done using specific name/value pairs. This expands
that to support a shared data attribute and dynamically get the type and
value of a click.
> Dynamic tracking

- assets/stylesheets/components/_selection-button.scss
- assets/stylesheets/units/_forms.scss
Specify the legend colour for IE7
Remove padding for selection buttons on less than IE9
> Fix: IE 7/8 form elements

- app/views/elements.nunjucks
- assets/stylesheets/components/_callout.scss
- assets/stylesheets/environment/settings/_colours.scss
- config/express.js
- content/conditions/hand-foot-and-mouth-disease/main-content.md
- content/conditions/shingles/main-content.md
- content/symptoms/headache/main-content.md
- content/symptoms/headache/sidebar-content.md
- content/symptoms/rashes-in-babies-and-children/main-content.md
- content/symptoms/rashes-in-babies-and-children/sidebar-content.md
- content/symptoms/stomach-ache/main-content.md
- content/symptoms/stomach-ache/sidebar-content.md
This adds 2 new levels of callout and amends existing references
to callouts
> Extend callout component to include 2 new variations

- config/config.js
- lib/logger.js
- package.json
Applicationinsights collects performance, usage data and exceptions so that related metrics can be accessed via Azure and alerts can be configured.
> Set up Application Insights

- app/views/_includes/local-header.nunjucks
- app/views/_layouts/content-sidebar-header.nunjucks
- app/views/_layouts/content-simple.nunjucks
- app/views/_macros/components.nunjucks
- assets/stylesheets/components/_local-header.scss
- assets/stylesheets/components/_section-unit.scss
- assets/stylesheets/components/_step-list.scss
- assets/stylesheets/nhsuk.scss
- assets/stylesheets/units/_links.scss
- content/conditions/hernia/main-content.md
- content/conditions/hernia/surgery-guide/manifest.json
- content/conditions/hernia/surgery-guide/preparing-for-your-pre-op/main-content.md
- content/conditions/hernia/surgery-guide/preparing-for-your-pre-op/manifest.json
- content/conditions/hernia/surgery-guide/recovery/main-content.md
- content/conditions/hernia/surgery-guide/recovery/manifest.json
- content/conditions/hernia/surgery-guide/section-1.md
- content/conditions/hernia/surgery-guide/section-2.md
- content/conditions/hernia/surgery-guide/section-3.md
- content/conditions/hernia/surgery-guide/section-4.md
- content/conditions/hernia/surgery-guide/section-5.md
- content/conditions/hernia/surgery-guide/section-6.md
- content/conditions/hernia/surgery-guide/section-7.md
- content/conditions/hernia/surgery-guide/seeing-the-surgeon/main-content.md
- content/conditions/hernia/surgery-guide/seeing-the-surgeon/manifest.json
- content/conditions/hernia/surgery-guide/the-day-of-your-surgery/main-content.md
- content/conditions/hernia/surgery-guide/the-day-of-your-surgery/manifest.json
This adds a new layout for surgery guides and includes content
for the first condition, hernia.
> Surgery guide

- app/controllers/redirect.js
- config/express.js
- config/routes.js
- package.json
- test/unit/controllers/redirect.test.js
This makes some changes to URL paths. 
- Removes trailing slashes
- Redirects empty containers
> URL updates

- .codeclimate.yml
- README.md
- npm-shrinkwrap.json
- package.json
Adding [codeclimate](https://codeclimate.com) to this repo allows us to get automated checks of
things like test coverage, code complexity, security issues with each merge.
This is the first configuration which may change with time.
This allows us to lock the dependencies so we're sure the correct
versions are deployed.
There was an issue with using the latest patch release of NPM v3
and NPM shrinkwrap. This issue had however been fixed in NPM v4
so this application was upgrade to use at least NPM v4
For more on the NPM 3.10.9 issue with npm-shrinkwrap see:
npm/npm#14042
> Add codeclimate config to set eslint engine

- README.md
- app.json
- app/views/_macros/components.nunjucks
- config/config.js
- config/express.js
- content/symptoms/stomach-ache/main-content.md
This uses an environment variable to map to a valid environment
of the connecting to services application.
> Set connecting to services url as environment variable

- app/views/error.nunjucks
- app/views/page-not-found.nunjucks
- config/express.js
Update the wording on the page not found and basic error pages.
This provides some extra options when hitting an error page.
> Improve error pages

- app/views/_includes/new-site-message.nunjucks
The new site message wording has been updated as a proportion of traffic will be coming straight through so the new wording caters for a wider range of journey.
> Update feedback banner wording

- app/views/_macros/components.nunjucks
- content/conditions/hand-foot-and-mouth-disease/main-content-before.md
This allows markup to be added to markdown files.
> Mark content from the API as safe

- .bowerrc
- bower.json
> Remove bower configs

- app/views/_includes/non-emergency-callout.nunjucks
- content/conditions/hand-foot-and-mouth-disease/manifest.json
Small update to some of the content for hand, foot and mouth disease.
> Content amends for hand, foot and mouth

- app/views/_layouts/content-simple.nunjucks
- app/views/_macros/components.nunjucks
When we're checking if a component is of a certain type before
doing something we need to make sure the string is in the case
that we expect. In this case, snake case.
> Convert component type checks to correct case

- app/views/_layouts/content-simple.nunjucks
- config/express.js
- content/conditions/earwax/main-content.md
- content/conditions/earwax/manifest.json
- content/conditions/indigestion/main-content.md
- content/conditions/indigestion/manifest.json
- content/conditions/insect-bites-and-stings/main-content.md
- content/conditions/insect-bites-and-stings/manifest.json
- content/conditions/insect-bites-and-stings/sidebar-content.md
- content/conditions/sore-throat/main-content.md
- content/conditions/sore-throat/manifest.json
- content/conditions/sore-throat/sidebar-content.md
- content/index/main-content.md
- package.json
Pending final copy.
[Trello card](https://trello.com/c/TFrMkxHQ/245-g2-publish-4-simple-conditions)
> Four new conditions

- app/views/_includes/feedback-message.nunjucks
- app/views/_includes/new-site-message.nunjucks
- app/views/_layouts/content-simple.nunjucks
- assets/javascripts/modules/feedback-form.js
- assets/javascripts/nhsuk.js
- gulp/tasks/dev/watch.js
- test/acceptance/pageobjects/feedback.page.js
- test/acceptance/specs/feedback.js
This involves adding a feedback prompt at the end of the content
as well as the top.
Adding to the bottom is a more logical place to ask for feedback as
a user has by this point read the content we're asking them to
feed back on.
- Does the interaction make sense when clicking the top link that you're scrolled down to the bottom of the page? _I feel it makes more sense than the opposite_
- Do we keep or drop the yellow background? _I was considering dropping the background but I think it helps visually show what has just changed so have kept it_
> Feedback position

- lib/content-store/file-handler.js
- test/unit/lib/content-store/file-handler.test.js
This adds support for the API file handler to support file
based includes within an array
> Support file loader within an array

- app/middleware/preview-api.js
As we removed the two column layout in favour of the 1 column stream, the related preview logic has to be updated.
> Update preview logic after content refactoring

- assets/stylesheets/components/_callout.scss
Changed info compact padding to use default padding on tablet/mobile. 
I can't build this repo locally, so I need someone else to test.
> changed .info--compact padding

- content/conditions/hay-fever/dont.md
> Change bullet point on Hay fever page

- content/conditions/earache/main-content-2.md
Some small content amends to the GP callout and service link
> Content changes to earache

- app/views/_components/text.nunjucks
- config/nunjucks.js
Needed to mark the value as safe from nunjucks so markdown can parse
correctly.
> Fix abbreviations in markdown

- app/middleware/feedback.js
- app/views/_components/form-multiple-choice.nunjucks
- app/views/_components/form-textbox.nunjucks
- app/views/_includes/feedback-form.nunjucks
- app/views/elements.nunjucks
- assets/javascripts/modules/conditional-subfields.js
- assets/javascripts/modules/label-focus.js
- assets/javascripts/modules/label-select.js
- assets/javascripts/nhsuk.js
- assets/stylesheets/components/_form-label.scss
- assets/stylesheets/components/_form-multiple-choice.scss
- assets/stylesheets/components/_form-textbox.scss
- assets/stylesheets/environment/tools/_utilities.scss
- assets/stylesheets/nhsuk.scss
- assets/stylesheets/units/_forms.scss
- test/acceptance/pageobjects/feedback.page.js
- test/acceptance/specs/feedback.js
- test/unit/components/form-multiple-choice.test.js
- test/unit/components/form-textbox.test.js
The current responses we get from page feedback isn't benefitting us enough.
This change uses an option list for what theme users can to the page for instead of an open question. It also asks what we can improve.
> Feedback update
