- assets/stylesheets/environment/generic/_box-sizing.scss
- assets/stylesheets/environment/tools/_placeholders.scss
- gulp/tasks/css.js
Two specific things for discussion:
To get rid of lint formatting warnings, this code:
```
*, *:before, *:after {
box-sizing: inherit;
}
```
would need to look something like this:
```
* {
&,
&:before,
&:after {
box-sizing: inherit;
}
}
```
...this seems less grokable to me.
Second, for the time being I'm gaming Autoprefixr like this:
```
browsers: ['> 0%', 'IE 8']
```
...meaning we're outputting vendor prefixes no matter what. Once we've made a formal support decision we can look at the use of Autoprefixr (or not) and the settings we need.
Thoughts?
> Set box sizing to border-box

- assets/stylesheets/components/_callout.scss
- assets/stylesheets/components/_global-footer.scss
- assets/stylesheets/components/_global-header.scss
- assets/stylesheets/components/_local-header.scss
- assets/stylesheets/components/_skiplinks.scss
- assets/stylesheets/environment/settings/_grid-layout.scss
- assets/stylesheets/environment/tools/mixins/_conditionals.scss
- assets/stylesheets/environment/tools/mixins/_grid-layout.scss
- assets/stylesheets/environment/tools/placeholders/_grid-layout.scss
- assets/stylesheets/environment/tools/placeholders/_shims.scss
- assets/stylesheets/nhsuk-print.scss
- assets/stylesheets/nhsuk.scss
- assets/stylesheets/objects/_main-content.scss
Add initial settings, helpers and mixins for creating basic grid based layouts. 
Includes:
* settings for max width and gutter
* helpers for indented site width containers, grid rows and full width containers
* mixin for creating grid columns
> Add initial grid support

- config/config.js
- config/express.js
Azure has a different way of signalling if encrypted connections so we need to check for an Azure specific environment variable in order to turn this one when the app is being served by Azure.
> Signal if azure environment to SSL redirect

- app/views/_includes/global/footer.nunjucks
Whilst there is uncertainty around the content license we need to
remove the OGL license statement
> Remove OGL license

- assets/stylesheets/units/_lists.scss
Before:
After:
Before:
After:
Also see the `/elements` page:
> Left align lists, also add a dram of space to ol > li

- assets/stylesheets/nhsuk.scss
- assets/stylesheets/units/_inline.scss
> Reduce weight of <abbr> underline

- app.json
Heroku doesn't support shorthand for multi buildpacks buildpack
references
> Use full url for Heroku multi buildpacks

- test/unit/.eslintrc
- test/unit/common.js
- test/unit/controllers/healthcheck.test.js
- test/unit/lib/git-lookup.js
This updates how unit tests run. It adds sinon and proxyquire to the mocha
globals.
It also makes better use of sinon's sandboxes to clean up after itself.
> Update mocha setup

- config/express.js
Allows the app to load images from google-analytics.com domain which
are used for tracking
> Amend CSP policy to allow images from GA

- app/controllers/stomach-ache.js
- app/views/_includes/new-site-message.nunjucks
- test/unit/controllers/stomach-ache.test.js
Allow current content pages to go back to a specific destination on NHS Choices
> Set link back to equivalent NHS Choices pages

- gulp/tasks/lint.js
Rather than specifying all JS files from the root for the JS linter,
give it only the folders we're concerned with to improve performance.
This means it doesn't have to trawl every single folder in the application,
including ignored folders.
> Improve performance of linting

- assets/stylesheets/components/_local-header.scss
20% white tint, not 80%
*Before:* 
*After:*
> Tweak local header border colour

- .deployment
- deploy.sh
- package.json
This creates a custom bash script for azure to specifically run the gulp
build task rather than rely on it running post npm install.
It also involves adding a heroku specific command to make sure it is still
run on heroku review apps.
> Add custom azure deployment script

- app/middleware/csrf-token.js
- app/views/_includes/feedback-form.nunjucks
- config/express.js
- package.json
Uses the csurf express library to add csrf protection using middleware.
Some middlewares were re-ordered to allow error page to be displayed correctly
when the csrf middleware throws an error.
> Add CSRF protection

- app/middleware/affinity-cookie.js
- config/express.js
Azure sets a cookie to keep users connected to a particular instance. This is
something we're not using right now so are disabling that cookie.
See https://azure.microsoft.com/en-gb/blog/disabling-arrs-instance-affinity-in-windows-azure-web-sites/
> Disable ARRAffinity cookie

- assets/javascripts/modules/feedback-form.js
IE8 doesn't support .bind() for changing the context so switching to jQuery
to bind click handlers
> Don't use native .bind() method to allow for IE8 support

- app/views/_includes/local-header.nunjucks
- app/views/_layouts/content-page.nunjucks
- assets/stylesheets/components/_callout.scss
- assets/stylesheets/components/_local-header.scss
- assets/stylesheets/environment/settings/_typography.scss
- assets/stylesheets/environment/tools/mixins/_conditionals.scss
- assets/stylesheets/environment/tools/mixins/_grid-layout.scss
- assets/stylesheets/environment/tools/placeholders/_layout.scss
- assets/stylesheets/nhsuk.scss
- assets/stylesheets/objects/_grid.scss
Tweaks to the grid, based on the fact that "tablet" as a breakpoint for this particular design isn't great. See grab:
To fix this, the "desktop" has been redefined at 925px, based on looking at the content we have in nhs-design.herokuapp.com - this is the start of a more content-out approach, rather than predefining "mobile", "tablet", "desktop". While these are useful to have as large general queries, we're going to want to be more component led than this.
Also added `$measure: 40em;` for comfortable reading width. This is used as a `reading-width` class when marking up grids.
> Tweak grid

- app/views/cookies.nunjucks
This change adds information about the cookies Webtrends tacking sets. It currently tweaks the wording originally used for just the google analytics information but may need to be separated out into its own section if that is too general.
> Add webtrends cookie information to cookies page

- webpack.production.config.js
Some browsers were throwing a `404` for the `.map` files as they were referenced in the bundle. 
Setting the webpack [devtool](https://webpack.github.io/docs/configuration.html#devtool) config item to `hidden-source-map` removes the reference in the bundles.
> Don't add source map reference in webpack production build

- package.json
- test/acceptance/pageobjects/content-page.page.js
- test/acceptance/pageobjects/feedback.page.js
- test/acceptance/pageobjects/page.js
- test/acceptance/specs/feedback.js
- test/acceptance/wdio.cloud.conf.js
- test/acceptance/wdio.conf.js
This adds an initial set of journeys for the feedback mechanism.
However, it cannot be currently tested with a successful submission until
a way to setup a dev environment for each instance is added.
- Are we happy to merge as is and do a separate PR when we have a way to use a dev instance to test successful submissions?
- Are the tests now taking too long? They're currently running at about 12-15mins and this is mainly because of the large amount of capabilities we're running against on Browserstack. Options are that we could reduce the amount of capabilities or leave and be happy with the longer time
> Add acceptance tests for basic feedback mechanism

- CONTRIBUTING.md
- README.md
We've moved the github organization from [github.com/nhsalpha](https://github.com/nhsalpha) to [github.com/nhsuk](https://github.com/nhsuk) so we need to update references to the old repositories within this one.
> Update references to old github organization

- assets/stylesheets/components/_section-unit.scss
- assets/stylesheets/environment/tools/mixins/_typography.scss
Top/bottom spacing was changing after 'tablet' but let/right spacing was
changing at 'desktop'. This keeps spacing breaks consistent and changes
spacing from 16px to 32px both at 'desktop'
> Fix consistency in spacing breakpoints

- app/views/_includes/global/head.nunjucks
- app/views/fungal-nail-infection.nunjucks
- assets/stylesheets/environment/settings/_fonts.scss
- assets/stylesheets/environment/settings/_globals.scss
- assets/stylesheets/environment/settings/_typography.scss
- assets/stylesheets/nhsuk-frutiger.scss
- assets/stylesheets/nhsuk-ie6-frutiger.scss
- assets/stylesheets/nhsuk-ie7-frutiger.scss
- assets/stylesheets/nhsuk-ie8-frutiger.scss
- config/express.js
We want to see how Frutiger compares to FS Me in our beta pages.
Adding in a template variable: `{% set font = "frutiger" %}`
If used, it'll pull in separate versions of `nhsuk.css`, all suffixed `-frutiger`
> Use Frutiger for some pages

- .eslintrc
- app/views/_includes/feedback-form.nunjucks
- app/views/_includes/new-site-message.nunjucks
- app/views/fungal-nail-infection.nunjucks
- app/views/rashes-in-babies-and-children.nunjucks
- assets/javascripts/modules/analytics.js
- assets/javascripts/nhsuk.js
This allows any changes to the global call to be managed in one place as
well as checking that the analytics object exists before making the call.
This PR fixes #116
> Extract webtrends onclick tracking to separate module

- app/views/_macros/images.nunjucks
- app/views/fungal-nail-infection.nunjucks
- app/views/rashes-in-babies-and-children.nunjucks
- config/express.js
Looking at a way to allow older IE (7 and 6) to fall back to simple image display.
While we’re not "officially" supporting these browsers, the markup pattern we're using means that a js-enabled browser will *not* display an image. This feels wrong to me, and somewhat against the principles of progressive enhancement.
*We're still going to have this issue with really really really old / non-evergreen browsers*
Think Netscape, IE5 and lower, you name it. I suggest we keep an eye on traffic and test accordingly. 
As a note, we've had 6 IE7 visitors since beta launch, none lower than that.
Onto the code:
```
<img
srcset="fever-and-red-cheeks-400.jpg 400w,
fever-and-red-cheeks-640.jpg 640w,
fever-and-red-cheeks-800.jpg 800w,
fever-and-red-cheeks-1280.jpg 1280w"
alt="A child’s face showing a …
```
> Conditional comment soup

- config/routes.js
I realised this check wasn't actually doing what it needed to because it was checking against the whole config object rather than the `env` property. Oops.
This fix makes sure the elements route is only served during development.
> Use correct check for serving elements route

- app/middleware/feedback.js
- package.json
This adds back in the IP address collection for feedback to add more advanced tracking with Webtrends.
This effectively "un-reverts" the original revert.
> Revert "Revert "Store user IP address in feedback""

- config/routes.js
This swaps the route search from a wildcard to include allowed routes so
unnecessary files like assets that can't be found don't get passed through
this controller first.
> Prevent assets from being routed through content controller

- content/conditions/type-2-diabetes/check-if-you-have-it/main-content.md
- content/conditions/type-2-diabetes/check-if-you-have-it/manifest.json
- content/conditions/type-2-diabetes/finding-help-and-support/main-content.md
- content/conditions/type-2-diabetes/finding-help-and-support/manifest.json
- content/conditions/type-2-diabetes/food-and-keeping-active/main-content.md
- content/conditions/type-2-diabetes/food-and-keeping-active/manifest.json
- content/conditions/type-2-diabetes/getting-diagnosed/main-content.md
- content/conditions/type-2-diabetes/getting-diagnosed/manifest.json
- content/conditions/type-2-diabetes/going-for-regular-check-ups/main-content.md
- content/conditions/type-2-diabetes/going-for-regular-check-ups/manifest.json
- content/conditions/type-2-diabetes/health-problems/main-content.md
- content/conditions/type-2-diabetes/health-problems/manifest.json
- content/conditions/type-2-diabetes/manifest.json
- content/conditions/type-2-diabetes/understanding-medication/main-content.md
- content/conditions/type-2-diabetes/understanding-medication/manifest.json
- content/index/main-content.md
Adds the type 2 diabetes guide content. 
This has been separated out to make it easier to review. 
It relies on #157 being merged first.
> Add diabetes type 2 guide

- gulp/tasks/rev.js
The updated gulp revision task now uses a whitelist so this adds the
files we're revisioning to that whitelist so they appear in the
manifest file used to serve the assets.
> Update gulp revision whitelist

- gulp/tasks/serve.js
- test/acceptance/wdio.conf.js
Removing this caused an error in the deployment task so adding back in.
> Use strict mode to allow block-scoped declarations

- content/conditions/type-2-diabetes/check-if-you-have-it/manifest.json
- content/conditions/type-2-diabetes/finding-help-and-support/manifest.json
- content/conditions/type-2-diabetes/food-and-keeping-active/manifest.json
- content/conditions/type-2-diabetes/getting-diagnosed/manifest.json
- content/conditions/type-2-diabetes/going-for-regular-check-ups/manifest.json
- content/conditions/type-2-diabetes/health-problems/manifest.json
- content/conditions/type-2-diabetes/understanding-medication/manifest.json
This creates the link back to NHS Choices pages for the Type 2 diabetes content.
> Add type 2 diabetes links back to Choices pages

- app/middleware/feedback.js
- app/views/_includes/feedback-form.nunjucks
- config/config.js
- lib/feedback-api.js
- test/unit/lib/feedback-api.js
This adds a timeout to the feedback API call that can be changed
per environment.
It also persists the comment the user has entered through any errors.
> Add timeout to feedback API and persist comment

- assets/stylesheets/components/_inline-list.scss
- assets/stylesheets/units/_lists.scss
This tidies the spacing of inline lists on smaller devices. 
**Before:**
No spacing between elements when on mobile
**After:**
Uses same spacing as lists within rest of layout
> Tidy spacing on footer lists

- gulp/tasks/serve.js
Prevents double server restart when changing files within `assets/`
> Don't restart server on frontend asset changes

- app/middleware/feedback.js
- app/views/_includes/feedback-form.nunjucks
- app/views/_includes/new-site-message.nunjucks
- app/views/elements.nunjucks
- assets/javascripts/modules/analytics.js
- assets/javascripts/modules/label-focus.js
- assets/javascripts/modules/label-select.js
- assets/javascripts/nhsuk.js
- assets/stylesheets/components/_callout.scss
- assets/stylesheets/components/_selection-button.scss
- assets/stylesheets/environment/tools/mixins/_css3.scss
- assets/stylesheets/nhsuk.scss
- assets/stylesheets/units/_buttons.scss
- assets/stylesheets/units/_forms.scss
- test/acceptance/specs/feedback.js
Change the feedback wording to be more focused on what the user was looking for rather than what it missing. This also added a new field to capture about whether they feel they found what they were looking for.
Part of this change involved changing the error handling to support both fields being empty and creating a new pattern around radios/checkboxes.
> Change feedback data capture

- assets/stylesheets/components/_selection-button.scss
Currently before and after elements were being styled even when
javascript is not enabled/loaded meaning the default browser elements
would be hidden.
This ensures the style is only applied when the browser understands
javascript is available.
> Bugfix: Fixes non-js layout of selection buttons

- package.json
Webpack 1.3.3 updated Uglify to 2.74 which now includes the --screw-ie8
flag by default:
https://github.com/mishoo/UglifyJS2/commit/02c638209ee22816b1324ff0c0f47b27db1336af
This now throws an error in IE8 builds which we don't want so for now
we're pinning the package - will need to find a better solution.
> Pin webpack to avoid UglifyJS being updated

- assets/stylesheets/components/_step-list.scss
The numbers within the step list sit outside of the step item element
so some padding is added to the container to allow sibling spacing to
be more consistent.
> Amend step list spacing

- assets/stylesheets/environment/generic/_shared.scss
During the global footer update the html background colour was missed
so if content doesn't fill the browser height it will display a
different colour
> Update html background colour to match footer

- config/express.js
This serves a favicon.ico file at the root so that browsers that don't
support the <link rel="icon"> declaration will not cause a mass of
404 requests to the server
> Serve favicon at root

- .codeclimate.yml
Ignore vendor assets and tests from codeclimate scans and add
paths to files to be rated.
> Update codeclimate config

- app/controllers/redirect.js
- app/middleware/content-api.js
- package.json
- test/unit/controllers/redirect.test.js
If a querystring was added to the URL it would return a 404 which is not the correct behaviour. 
This was happening because we were looking for the full url in the views or content folder. 
This change uses the path property which does not contain any querystring parameters. 
Fixes #203
> Allow content-api request to support querystrings and not 404

- app/views/_includes/new-site-message.nunjucks
This prevents users from ending up in a redirect loop if they choose to
go back to the equivalent Choices page after already having been
redirected.
> Use query string parameter to skip beta redirect

- content/conditions/fungal-nail-infection/main-content.md
The original wording around actions to take to prevent fungal nail infection was slightly confusing as it included a combination of "you should" and "don't". 
We've removed "you should" so the actions read better.
> Amend fungal nail wording to be less confusing

- gulp/tasks/serve.js
Can be used with either [node-inspector](https://github.com/node-inspector/node-inspector) or WebStorm.
> Add --debug arg to nodemon to be able to run a debugging session

- assets/stylesheets/nhsuk.scss
- gulp/tasks/build/css.js
Previous [PR](https://github.com/nhsuk/betahealth/pull/226) had an import reference to deleted mixin which was showing Sass error in console but allowed the build to complete. This allowed to deploy site without styles.
> Break on Sass error

- app/views/_md-filters/alert.nunjucks
- app/views/_md-filters/attention.nunjucks
- app/views/_md-filters/info.nunjucks
- app/views/_md-filters/info_compact.nunjucks
- app/views/_md-filters/inline_reveal.nunjucks
- app/views/_md-filters/reveal.nunjucks
- app/views/_md-filters/severe.nunjucks
- app/views/_md-filters/warning.nunjucks
- config/express.js
- gulp/tasks/dev/watch.js
- lib/custom-md-filter.js
- package.json
- test/unit/lib/custom-md-filter.js
We use [MarkdownIt Containers](https://github.com/markdown-it/markdown-it-container) extension  to create custom filters in MD documents which are expanded into custom fragments with custom HTML wrappers.
This PR moves HTML out of JS and makes use of Nunjucks. It also allows to pass key/value parameters to template to set additional context.
[Trello card](https://trello.com/c/7FsMi4Z5/217-improve-code-for-custom-markdown-filters)
> Markdown custom containers

- README.md
- config/config.js
- config/routes/image-proxy-router.js
- lib/content-store/rest-handler.js
- test/unit/lib/content-store/rest-handler.test.js
There may be a case we want to use separate services for the two so
this allows the image base url to be updated without affecting the
content API
> Separate content store and image store config

- Gemfile.lock
The Gemfile.lock uses a newer version of scss_lint that we want to
use right now.
> Ensure Gemfile.lock contains correct version of scss_lint

- lib/content-store/fallback-handler.js
- lib/content-store/index.js
- test/unit/lib/content-store/fallback-handler.test.js
This handler will use the REST handler first to find a record
but then fallback to the File System if it cannot get a record.
If neither returns a record it rejects the promise.
> Add fallback handler for both REST and File System

- app/middleware/preview-api.js
- lib/content-store/rest-handler.js
The code only replaced the first occurrence of unsafe chars meaning that the resulting signature did not match the backend one.
I wrote a test nodejs script that generates random signatures and calls an equivalent python one to check that they match.
**nodejs script**
```javascript
const crypto = require('crypto');
const spawn = require('child_process').spawn;
const PREVIEW_SIGNATURE_KEY = 'mxwtt97p8[)89+Qm8xwMWTXK](Qc&MhdT=dW72bfhL/du4({sR';
function generateSignature(pageId, revisionId) {
const message = `${pageId}/${revisionId}/`;
const hmacSha1 = crypto.createHmac('sha1', PREVIEW_SIGNATURE_KEY).update(message).digest('base64');
return hmacSha1.replace(/\+/g, '-').replace(/\//g, '_');
}
for (let i = 0; i <= 100; i++) {
const pageId = Math.random();
const revisionId = Math.random(); …
```
> Replace all unsafe chars in preview signatures

- app/views/elements.nunjucks
- assets/stylesheets/components/_panel.scss
- assets/stylesheets/units/_lists.scss
This adds a new panel variation which supports 2 columns, for example for a do's and don'ts comparison.
Adds 2 new list variations for a green tick and a red cross, for example to highlight do's and don'ts lists.
> Components

- app/views/_macros/components.nunjucks
This allows the split panel, which stacks on small screen widths
and display inline on wider widths, to be support via the API.
> Add split panel component macro support

- app/views/_macros/components.nunjucks
- app/views/elements.nunjucks
- assets/stylesheets/components/_panel.scss
Panels should be allowed to use the full space if required.
Where we're currently using the default panel styling we
will continue to restrict its width. But this can be done
using the reading-width class.
> Remove reading width restriction from panel component

- assets/javascripts/modules/analytics.js
This prevents a reference error when checking for the Webtrends
object globally
> Check for existence of Webtrends object on window

- app/views/_includes/local-header.nunjucks
- content/conditions/constipation/local-header.md
- content/conditions/dehydration/local-header.md
- content/conditions/diarrhoea/local-header.md
We currently use a custom data attribute to track in-page anchor
links.
This was being added when using the section_nav component but gets
missed when manually adding anchor navigation to the local header.
This temporarily adds the correct attribute to the existing navigation
items but will need a better long term fix. This fix may well be applied
at the publisher/content store end.
> Ensure all in-page anchor links have tracking attribute

- gulp/tasks/shared/css.js
- package.json
`node-sass-import-once` module allows to:
- remove import duplicates defined in multiple places
- import directory indexes via `_index.scss` (e.g. `@import "units"` will import `units/_index.scss`)
> Add node-sass-import-once as Sass importer

- public/robots.txt
This change adds a basic [robots.txt](http://www.robotstxt.org/) file. It will prevent 404 errors showing in logs when this file is hit.
It also allows a base file to declare any future definitions for beta.nhs.uk.
> Add basic robots.txt file

- assets/stylesheets/components/_selection-button.scss
Some changes had been made to the base we used for selection buttons
from GDS. This PR documents a lot of the considerations that were
made during developing this component:
https://github.com/alphagov/govuk_elements/pull/296/
Specifically, these commits:
- [Fix radios / checkboxes in Dragon NaturallySpeaking 13](https://github.com/alphagov/govuk_elements/pull/296/commits/f1fdcc45516c91e124e5476c12d7ff0994dd9374)
- [Custom radios / checkboxes](https://github.com/alphagov/govuk_elements/pull/296/commits/4e50e9bf44fadc42b1e5ac0737ad72a727a77fce)
> Update selection button

- app/views/_includes/global/header.nunjucks
[Reasons](https://silktide.com/i-thought-title-text-improved-accessibility-i-was-wrong/).
> Move link title from logo's anchor to image `alt`

- content/conditions/constipation/main-content.md
- content/conditions/constipation/manifest.json
- content/conditions/heat-exhaustion-and-heatstroke/main-content.md
- content/conditions/heat-exhaustion-and-heatstroke/manifest.json
Currently we use the 111 callout at the foot of the content. These two
content items embed that content in the page. We are going to do an
overall review of the placement of the 111 banner but for now we should
be consistent in our use of it.
> Update 111 callout consistency

- app/views/_includes/global/head.nunjucks
Twitter card metadata was using `value` instead of `content` for the
value property. This fixes that issue.
> Use correct attribute for metadata

- README.md
- app/middleware/development.js
- config/config.js
This change allows an variable to be set on the environment to display routes that by default we don't want available. For example, a view showing all the elements or components.
> Add ability to show development routes if NODE_ENV=production

- test/unit/component-helper.js
- test/unit/components/text.test.js
After realising we missed when some markdown extensions broke, this adds
some tests to make sure that when syntax for new extensions is used
it returns what is expected.
> Improve markdown text component tests

- content/conditions/cough/manifest.json
- content/conditions/dehydration/callout-emergency.md
- content/conditions/diarrhoea/callout-gp-babies.md
- content/conditions/diarrhoea/callout-gp.md
- content/conditions/diarrhoea/callout-urgent-babies.md
- content/conditions/earache/callout-gp.md
- content/conditions/hand-foot-and-mouth-disease/callout-gp.md
- content/conditions/heat-exhaustion-and-heatstroke/callout-emergency.md
- content/conditions/hives/callout-emergency.md
- content/conditions/indigestion/callout-gp.md
- content/conditions/indigestion/main-content-3.md
- content/conditions/insect-bites-and-stings/callout-emergency.md
- content/conditions/mouth-ulcers/callout-gp.md
- content/conditions/sore-throat/callout-emergency.md
- content/conditions/sprains-and-strains/callout-emergency.md
- content/conditions/sprains-and-strains/callout-gp.md
- content/conditions/sprains-and-strains/callout-service-link-3.md
- content/conditions/sprains-and-strains/manifest.json
- content/conditions/warts/callout-gp.md
- content/conditions/warts/callout-service-link.md
- content/conditions/warts/manifest.json
We've used horizontal rules (`hr`) where they don't semantically make
sense.
This change improves the use of hr's across the beta content pages.
> Improve consistency of content patterns

- app/controllers/components-controller.js
The controller was resetting the family key if it didn't match the
previous which meant some components were being lost. It should
have just been checking for the existence of that key before
setting a new empty array.
This change fixes that bug.
> Fix issue with components controller

- content/conditions/broken-or-bruised-ribs/manifest.json
Wrong callout style used on emergency callout on broken ribs
> Update callout style from alert to severe

- app/views/_components/reveal.nunjucks
- assets/stylesheets/units/_details.scss
- assets/stylesheets/units/_tables.scss
- test/unit/components/reveal.test.js
This adds an indentation and left border to distinguish text
that has been revealed.
**[EDIT]:** This is no longer an issue after the changes made in #334.
The image cards now stack when this extra padding is included. This could potentially be addressed by an alternative way of removing the images from the reveal and using a different method to hide/show more graphic images. We have discussed using a blur and an action to reveal the image.
The more we nest content the less readable it seems to become. Maybe an alternative is to review the use of the side by side lists when they have large amounts of content and a reveal like this.
> Update hidden text component
